phrase:
  project_id: 7cc193b28c133e93c5fe55294c1e90c1
  push:
    sources:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
          locale_id: en
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
