phrase:
  access_token: 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
  project_id: 7852f70b8c151e1741f03215061aee0e
  push:
    sources:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
          locale_id: en
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ./<locale_name>.xlf
        params:
          file_format" xlf
